<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>ApproachR10Windows</AssemblyName>
    <RootNamespace>ApproachR10Windows</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="r10-adapter/gspro-r10.csproj" />
  </ItemGroup>
</Project>
