using Google.Protobuf;
using InTheHand.Bluetooth;
using LaunchMonitor.Proto;
using System.Collections.Concurrent;
using System.Text;
using ApproachR10Windows.R10Protocol;
namespace ApproachR10Windows.R10;
public abstract class BaseDevice : IDisposable {
 static readonly Guid BatteryService=Guid.Parse("0000180f-0000-1000-8000-00805f9b34fb"),BatteryCharacteristic=Guid.Parse("00002a19-0000-1000-8000-00805f9b34fb"),DeviceInfoService=Guid.Parse("0000180a-0000-1000-8000-00805f9b34fb"),FirmwareCharacteristic=Guid.Parse("00002a28-0000-1000-8000-00805f9b34fb"),ModelCharacteristic=Guid.Parse("00002a24-0000-1000-8000-00805f9b34fb"),SerialCharacteristic=Guid.Parse("00002a25-0000-1000-8000-00805f9b34fb"),InterfaceService=Guid.Parse("6A4E2800-667B-11E3-949A-0800200C9A66"),InterfaceNotifier=Guid.Parse("6A4E2812-667B-11E3-949A-0800200C9A66"),InterfaceWriter=Guid.Parse("6A4E2822-667B-11E3-949A-0800200C9A66");
 public BluetoothDevice Device{get;} public int Battery{get;private set;} public string? Model{get;private set;} public string? Firmware{get;private set;} public string? Serial{get;private set;}
 readonly ConcurrentQueue<byte[]> writerQueue=new(),readerQueue=new(),processQueue=new(); readonly AutoResetEvent writerSignal=new(false),readerSignal=new(false),processSignal=new(false); readonly ManualResetEventSlim handshake=new(false),response=new(false); readonly CancellationTokenSource cancel=new();
 IMessage? lastResponse; int requestCounter; byte header; GattCharacteristic? writer; readonly Task writerTask,readerTask,processTask; bool disposed;
 public bool DebugLogging{get;set;} public event Action<int>? BatteryUpdated; public event Action<IMessage>? MessageReceived;
 protected BaseDevice(BluetoothDevice device){Device=device;writerTask=Task.Run(WriterLoop);readerTask=Task.Run(ReaderLoop);processTask=Task.Run(ProcessLoop);}
 public virtual bool Setup(){var info=Device.Gatt.GetPrimaryServiceAsync(DeviceInfoService).WaitAsync(TimeSpan.FromSeconds(5)).Result;Serial=Encoding.ASCII.GetString(info.GetCharacteristicAsync(SerialCharacteristic).Result.ReadValueAsync().Result);Firmware=Encoding.ASCII.GetString(info.GetCharacteristicAsync(FirmwareCharacteristic).Result.ReadValueAsync().Result);Model=Encoding.ASCII.GetString(info.GetCharacteristicAsync(ModelCharacteristic).Result.ReadValueAsync().Result);var battery=Device.Gatt.GetPrimaryServiceAsync(BatteryService).WaitAsync(TimeSpan.FromSeconds(5)).Result.GetCharacteristicAsync(BatteryCharacteristic).Result;battery.CharacteristicValueChanged+=(s,e)=>{Battery=e.Value[0];BatteryUpdated?.Invoke(Battery);};battery.StartNotificationsAsync().Wait(TimeSpan.FromSeconds(5));var service=Device.Gatt.GetPrimaryServiceAsync(InterfaceService).WaitAsync(TimeSpan.FromSeconds(5)).Result;writer=service.GetCharacteristicAsync(InterfaceWriter).WaitAsync(TimeSpan.FromSeconds(5)).Result;var notifier=service.GetCharacteristicAsync(InterfaceNotifier).WaitAsync(TimeSpan.FromSeconds(5)).Result;notifier.StartNotificationsAsync().Wait(TimeSpan.FromSeconds(5));notifier.CharacteristicValueChanged+=(s,e)=>{readerQueue.Enqueue(e.Value);readerSignal.Set();};return PerformHandshake();}
 bool PerformHandshake(){handshake.Reset();header=0;SendBytes("000000000000000000010000".ToByteArray());return handshake.Wait(TimeSpan.FromSeconds(10));}
 void WriterLoop(){while(!cancel.IsCancellationRequested){if(writerQueue.TryDequeue(out var b))_ = writer?.WriteValueWithResponseAsync(b);else writerSignal.WaitOne(500);}}
 void ReaderLoop(){var current=new List<byte>();while(!cancel.IsCancellationRequested){if(!readerQueue.TryDequeue(out var msg)){readerSignal.WaitOne(500);continue;}var h=msg.First();var body=msg.Skip(1).ToArray();if(h==0||!handshake.IsSet){if(body.ToHexString().StartsWith("010000000000000000010000")){header=body[12];SendBytes("00".ToByteArray());handshake.Set();}continue;}bool complete=body.LastOrDefault()==0;if(complete)body=body[..^1];if(body.Length>0&&body[0]==0){current.Clear();body=body[1..];}current.AddRange(body);if(complete&&current.Count>0){processQueue.Enqueue(Cobs.Decode(current).ToArray());processSignal.Set();current.Clear();}}}
 void ProcessLoop(){while(!cancel.IsCancellationRequested){if(processQueue.TryDequeue(out var frame))ProcessFrame(frame);else processSignal.WaitOne(500);}}
 void ProcessFrame(byte[] frame){if(frame.Length<6)return;var msg=frame[2..^2];var hex=msg.ToHexString();var ack=new List<byte>{0};if(hex.StartsWith("B413")){ushort counter=BitConverter.ToUInt16(msg[2..4]);ack.AddRange(msg[2..4]);ack.AddRange("00000000000000".ToByteArray());if(counter==requestCounter){lastResponse=WrapperProto.Parser.ParseFrom(msg[16..]);MessageReceived?.Invoke(lastResponse);response.Set();}}else if(hex.StartsWith("B313")){ack.AddRange(msg[2..4]);ack.AddRange("00000000000000".ToByteArray());var request=WrapperProto.Parser.ParseFrom(msg[16..]);MessageReceived?.Invoke(request);HandleProtobufRequest(request);}Acknowledge(msg,ack);}
 void Acknowledge(byte[] msg,List<byte> body)=>WriteMessage("8813".ToByteArray().Concat(msg.Take(2)).Concat(body).ToArray());
 public IMessage? SendProtobufRequest(IMessage proto){response.Reset();var bytes=proto.ToByteArray();var full="B313".ToByteArray().Concat(BitConverter.GetBytes(requestCounter)).Append((byte)0).Append((byte)0).Concat(BitConverter.GetBytes(bytes.Length)).Concat(BitConverter.GetBytes(bytes.Length)).Concat(bytes).ToArray();WriteMessage(full);if(response.Wait(5000)){requestCounter++;return lastResponse;}return null;}
 void SendBytes(IEnumerable<byte> bytes){writerQueue.Enqueue(bytes.Prepend(header).ToArray());writerSignal.Set();} public void SendBytes(string hex)=>SendBytes(hex.ToByteArray());
 public void WriteMessage(byte[] bytes){ushort len=(ushort)(bytes.Length+4);var framed=BitConverter.GetBytes(len).Concat(bytes).Concat(bytes.Checksum()).ToArray();var encoded=Cobs.Encode(framed).Prepend((byte)0).Append((byte)0).ToList();while(encoded.Count>19){SendBytes(encoded.Take(19));encoded=encoded.Skip(19).ToList();}if(encoded.Count>0)SendBytes(encoded);}
 public abstract void HandleProtobufRequest(IMessage request);
 public void Dispose(){if(disposed)return;disposed=true;cancel.Cancel();writerSignal.Set();readerSignal.Set();processSignal.Set();try{Task.WaitAll([writerTask,readerTask,processTask],2000);}catch{}try{Device.Gatt.Disconnect();}catch{}}
}
